import 'dart:io';
import 'package:auto_route/auto_route.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:hwzn_base/general/constants/modals/LoadingDialog.dart';
import 'package:hwzn_base/general/helper/configration/CustomButtonAnimation.dart';
import 'package:hwzn_base/general/helper/helper_methods/HelperMethods.dart';
import 'package:hwzn_base/general/models/dropdown_model/dropdown_model.dart';
import 'package:hwzn_base/general/packages/generic_bloc/generic_cubit.dart';
import 'package:hwzn_base/general/resources/GeneralRepoImports.dart';
import 'package:hwzn_base/general/screens/register/widgets/RegisterWidgetsImports.dart';
import 'package:hwzn_base/general/utilities/routers/RouterImports.gr.dart';
import 'package:hwzn_base/general/utilities/utils_functions/AdaptivePicker.dart';
import 'package:hwzn_base/general/widgets/AuthAppBar.dart';
import 'package:intl/intl.dart';
import '../../constants/custom_ drop_down/CustomDropDown.dart';
import '../../models/toJson/RegisterModel.dart';
import '../../utilities/utils_functions/UtilsImports.dart';
import '../../widgets/AuthScaffold.dart';

part 'Register.dart';
part 'RegisterData.dart';