/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String apple = "assets/images/apple.svg";
  static const String ar = "assets/lang/ar.json";
  static const String arrow = "assets/images/arrow.svg";
  static const String en = "assets/lang/en.json";
  static const String facebook = "assets/images/facebook.svg";
  static const String icon = "assets/images/icon.png";
  static const String logo = "assets/images/logo.png";
  static const String marker = "assets/images/marker.png";
  static const String mobile = "assets/images/mobile.svg";
  static const String onboardingOne = "assets/images/onboardingOne.jpg";
  static const String onboardingThree = "assets/images/onboardingThree.jpg";
  static const String onboardingTwo = "assets/images/onboardingTwo.jpg";
  static const String password = "assets/images/password.svg";
  static const String twitter = "assets/images/twitter.png";
  static const String upload = "assets/images/upload.png";
}
